# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
orbs:
  node: circleci/node@5.0.2

jobs:
  backend:
    executor: node/default
    
    working_directory: ~/APDSPEO/secure-login-portal
    steps:      
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  
  frontend:
    executor: node/default
    working_directory: ~/apds7311-poe-vctickettracker/APDSPEO/secure-login-frontend
    steps:  
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
      
workflows:
  sample: 
    jobs:
      - frontend
      - backend

