# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "WorkFlow" ]
  pull_request:
    branches: [ "main", "WorkFlow" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use secure-login-portal
      uses: actions/setup-node@v4
      with:
        # Set always-auth in npmrc.
        always-auth: false # optional, default is false
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: '20.x'# optional
        # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
        cache: npm # optional
        # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
        cache-dependency-path: APDSPEO\secure-login-frontend\package-lock.json, APDSPEO\secure-login-frontend\package-lock.json # optional
    - run: |
            npm install
    - run: |
            npm run build --if-present
    - run: |
            npm test

    - name: Use secure-login-frontend
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - run: |
            cd APDSPEO\secure-login-frontend
            npm install
    - run: |
            cd APDSPEO\secure-login-frontend
            npm run build --if-present
    - run: |
            cd APDSPEO\secure-login-frontend
            npm test
